"2025" = [
    "D - ઢોલ ઢમક્યા ને",
    "G - ગણેશ પાટ બેસાડીએ",
    "K - કેસરિયો જાન લાવ્યો",
    "L - લાડો લાડી જમે રે કંસાર",
    "M - મંગલાષ્ટક",
    "M - મારા નખના પરવાળા જેવી",
    "N - નાણાવટી રે સાજન બેઠું માંડવે",
    "P - પરથમ ગણેશ બેસાડો રે",
    "P - પહેલું પહેલું મંગળિયું વરતાય રે",
    "S - સીતાને તોરણ રામ પધાર્યાં",
    "V - વરરાજે સીમડી ઘેરી",
]
